### ISSUE TITLE
Using `front-matter` npm module

### ISSUE THREAD

**Issue by thom4parisot** [assemble/assemble-yaml#12]
Hello,

is there any reason why this module implements its own way of parsing YAML Front Matter instead of using [front-matter](https://github.com/jxson/front-matter)?

Thanks :-)

**Comment by doowb** [comment]
We pulled this out of the assemble repo to be useful in other projects. When we first put it in the assemble repo, it looks like it was when that front-matter repo was just starting out and we had decided to use js-yaml instead of yamlparser, but we needed to pull out the front matter on our own.

It's just evolved from there. Also, this is used in assemble-front-matter, which we've discussed extending that to use different types of "front matter" and not just yaml. We'd like to be able to include different types of fence delimiters to specify language if needed.

Other than that, I remember seeing front-matter at one time and thinking there was something that either didn't work for us or something I didn't like, but I don't remember what it was.

**Comment by jonschlinkert** [comment]
What is the advantage of that repo?

**Comment by jonschlinkert** [comment]
I'd like to stick with this lib since it's core to Assemble, but I also think it needs to be refactored. [How about this](https://github.com/jonschlinkert/yfm-test/blob/master/index.js)?

**Comment by thom4parisot** [comment]
Well the initial question was very naive, obviously to ask for the context :-)
The benefit of `front-matter` is to do the parsing for you. I guess this is the goal you achieve with `js-yaml`.

There is no problem not using though :-)

**Comment by jonschlinkert** [comment]
:+1: ok, no worries. we don't mind the dialog
